# Generated by Django 3.2.5 on 2022-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
