# Generated by Django 3.2.5 on 2022-03-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genra',
            new_name='genre',
        ),
    ]
