# Generated by Django 3.2.5 on 2022-04-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(max_length=520),
        ),
    ]
