# Generated by Django 3.2.5 on 2022-04-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
