# Generated by Django 3.2.5 on 2022-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbookaveragerating',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
