# Generated by Django 4.0.2 on 2022-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='club_role',
            field=models.CharField(choices=[('MEM', 'Member'), ('MOD', 'Moderator'), ('OWN', 'Owner'), ('BAN', 'BannedMember')], default='MEM', max_length=3),
        ),
    ]
