# Generated by Django 3.2.5 on 2022-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genra',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
