# Generated by Django 3.2.5 on 2022-02-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_club_role_club_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='genre',
            field=models.CharField(default='', max_length=520),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_status',
            field=models.BooleanField(choices=[(True, 'Online'), (False, 'In Person')], default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='public_status',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=520)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'club')},
            },
        ),
    ]
