# Generated by Django 3.2.5 on 2022-03-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_rename_genra_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genra',
        ),
    ]
