# Generated by Django 3.2.5 on 2022-02-17 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_alter_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=120)),
                ('description', models.TextField(blank=True, max_length=520)),
                ('meeting_status', models.BooleanField(choices=[(True, 'Online'), (False, 'In Person')], default=False)),
                ('location', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclubs.book')),
                ('chooser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_chooser', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_club', to='bookclubs.club')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_role', models.CharField(choices=[('H', 'Host'), ('C', 'Chooser'), ('A', 'Attendee')], max_length=1)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclubs.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
