# Generated by Django 3.2.5 on 2022-02-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0003_book_genra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.CharField(max_length=100),
        ),
    ]
