# Generated by Django 3.2.5 on 2022-03-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0003_auto_20220322_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
