# Generated by Django 4.0.2 on 2022-02-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_alter_role_club_role'),
        ('bookclubs', '0003_meeting_meetingattendance'),
    ]

    operations = [
    ]
