# Generated by Django 3.2.5 on 2022-03-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_alter_role_club_role'),
        ('bookclubs', '0003_rename_genre_book_genra'),
    ]

    operations = [
    ]
