# Generated by Django 3.2.5 on 2022-02-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0004_auto_20220223_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(),
        ),
    ]
