# Generated by Django 3.2.5 on 2022-03-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0004_auto_20220312_2143'),
        ('bookclubs', '0004_merge_20220312_1702'),
    ]

    operations = [
    ]
