# Generated by Django 3.2.5 on 2022-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0005_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meeting_preference',
            field=models.CharField(blank=True, choices=[('O', 'Online'), ('P', 'In-person')], max_length=1),
        ),
    ]
