# Generated by Django 3.2.5 on 2022-03-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0005_merge_20220313_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genra',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting_status',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'In-person')], max_length=3),
        ),
        migrations.AlterField(
            model_name='club',
            name='public_status',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], max_length=3),
        ),
    ]
