# Generated by Django 3.2.5 on 2022-03-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0006_auto_20220314_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meeting_status',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'In-person')], default='OFF', max_length=3),
        ),
        migrations.AlterField(
            model_name='club',
            name='public_status',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PRI', max_length=3),
        ),
    ]
