# Generated by Django 3.2.5 on 2022-03-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0007_auto_20220314_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meeting_preference',
            field=models.CharField(blank=True, choices=[('ONL', 'Online'), ('OFF', 'In-person')], max_length=3),
        ),
    ]
