# Generated by Django 3.2.5 on 2022-03-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0008_alter_user_meeting_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meeting_preference',
            field=models.CharField(blank=True, choices=[('O', 'Online'), ('P', 'In-person')], max_length=1),
        ),
    ]
