# Generated by Django 3.2.5 on 2022-02-08 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0009_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
