# Generated by Django 3.2.5 on 2022-03-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0009_alter_user_meeting_preference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('user', 'meeting')},
        ),
    ]
