# Generated by Django 4.0.2 on 2022-02-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0003_auto_20220207_1547'),
        ('bookclubs', '0010_post_post_datetime'),
    ]

    operations = [
    ]
