# Generated by Django 3.2.5 on 2022-02-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='related_post',
        ),
    ]
