# Generated by Django 3.2.5 on 2022-02-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0014_auto_20220209_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
